### ISSUE TITLE
Problem with testing components when component size has been changed

### ISSUE THREAD

**Issue by michalg42** [macku/jest-puppe-shots#7]
Hello
We have a problem with testing react components, when its size has been changed, in such case jest-image-snapshots throws error "toMatchImageSnapshot(): Received image size must match baseline snapshot size in order to make comparison."
In general that's not a problem when creating screenshot of whole page, but jest-puppe-shots makes screenshot of small part of it and it can differ in size in such case as adding new line to component.
I thought about always creating big screenshot (something like 1000x1000px) but comparision of such big screenshots takes too long.
I tried to come up with another solution, unfortunately I couldn't find any, so I could use any help with this issue. :)

**Comment by macku** [comment]
Hi @michalg42, In such a case you might just update the existing image snapshot with the [`--u`](https://facebook.github.io/jest/docs/en/cli.html#updatesnapshot) param passed to the jest CLI ex. `npm run test -- -u`

**Comment by michalg42** [comment]
Yeah, I know, the problem is I would like to check what has changed in these components. In all other I have image created by jest-image-snapshot I can can quickly check differences, here I only know something has changed and I can either believe everything is fine and run --u or check with master older commit.

I know that technically that's not a problem of jest-puppe-shots, unfortunatelly in issue in jest-image-snapshots there was answer that probably its user who should pre-process these images to match sizes.

**Comment by macku** [comment]
Yep, I will have to take a closer look into to the `jest-image-snapshots` library. I guess one of the solutions might be downsizing or resizing the snapshot for the comparison purpose. But then it could cut part of the image the is needed for the comparison.

**Comment by michalg42** [comment]
Problem with downsizing of snapshot is, as you told, it could cut part of the image and in some cases two different components can pass tests because of that (ass all changes you did to component were cut out of screenshot).

I had to fix this problem and I wrapped toMatchImageSnapshot with my own code - when this function returns error that images aren't equal I create diff image where there are both old and new screenshot (without difference pic), it solves my problem in some way as I can compare both versions on one image, but I used there part of jest-image-snapshot code and that wasn't too elegant solution...

**Comment by anescobar1991** [comment]
@michalg42 I am the maintainer of jest-image-snapshot and just wanted to let you know that I am working on a solution to this issue.

Should have something in next few days. Follow https://github.com/americanexpress/jest-image-snapshot/issues/49 for more details/updates :)

**Comment by michalg42** [comment]
I guess it can be closed now as it has been fixed in jest-image-snapshots v2.4.0

**Comment by macku** [comment]
@michalg42 Let me know if you manage to resolve the problem. You can also contribute to the project and update the FAQ in REAMDE for this case 😄

**Comment by michalg42** [comment]
Is this correct issue for that comment? As this problem was already resolved by new version of jest-image-snapshots so there is no problem to be fixed. :)
