### ISSUE TITLE
wrong reactRenderer keyname specified in doc

### ISSUE THREAD

**Issue by ovidiu-lapadus** [macku/jest-puppe-shots#8]
I had to use __JEST_PUPPE_SHOTS_RENDERER__ instead of __JEST_PUPPE_RENDERER__
as specified in readme
```
"globals": {
    "__JEST_PUPPE_SHOTS_RENDERER__": "STYLED_COMPONENTS"
}
```

**Comment by macku** [comment]
Thanks, @ovidiu-lapadus! I've fixed the typo and released 0.4.1
