### ISSUE TITLE
Mounting Additional CSS Example has error

### ISSUE THREAD

**Issue by daynedavis** [macku/jest-puppe-shots#9]
This example is not a valid use of path.resolve() and following this format will throw an error. 
```
 await page.mountCssContext(path.resolve('../path/to/my-assets-dir', [
    'css/reset.css',
    'css/custom-styles.css'
  ]))
```

I've tried altering it to this, but 
```
 await page.mountCssContext(path.resolve('build'), [
    'style.css'
  ])
```

But I am consistently getting the error `Error: loading style from build/style.css`. Can you provide an updated additional css example that is working correctly?

**Comment by macku** [comment]
Hi @daynedavis, yes, there is a typo in the README.txt thanks for pointing this out.

As for your question, I'm not sure what is the structure of your project but you should check if the path from the place where you have a test file to the `build` directory is correct.
Right now you are trying to resolve `build` directory from the same directory where your test file is located.

Maybe you need to provide a relative path instead and try to load `build` directory from the parent dir in your project structure? Example `path.resolve('../.../build')`?
